<a href="https://colab.research.google.com/github/jaewoong-87/python/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numerical python   N-dimentional 

In [1]:
import numpy as np

np.__version__

'1.19.5'

In [5]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))
print(a1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [10]:
a2=np.array([ [1, 2, 3], [4, 5, 6], [7,8,9]])
print(a2)
print(a2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


zero.shape

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [14]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [18]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.logspace(2,4,5)

array([  100.        ,   316.22776602,  1000.        ,  3162.27766017,
       10000.        ])

random value

In [20]:
np.random.random((3,3))

array([[0.32142125, 0.97615013, 0.74756168],
       [0.50877838, 0.04053941, 0.57109957],
       [0.94878326, 0.64128847, 0.88921835]])

In [23]:
np.random.randint(0,10, (3,3))

array([[4, 7, 3],
       [1, 3, 6],
       [0, 4, 4]])

In [24]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
a1=np.random.randint(1,9,(3,3))
print(a1)
print(a1[0:2])

[[5 7 2]
 [4 2 3]
 [3 2 8]]
[[5 7 2]
 [4 2 3]]


In [32]:
b1 =np.insert(a1,0,10)
print(b1)

[10  5  7  2  4  2  3  3  2  8]


In [35]:
b2 = np.insert(a1, 1, 10, axis=0)
print(b2)
c2 = np.insert(a1, 1, 10, axis=1)
print(c2)

[[ 5  7  2]
 [10 10 10]
 [ 4  2  3]
 [ 3  2  8]]
[[ 5 10  7  2]
 [ 4 10  2  3]
 [ 3 10  2  8]]


In [36]:
print(a1)
a1[0]=1
a1[1]=5
print(a1)

[[5 7 2]
 [4 2 3]
 [3 2 8]]
[[1 1 1]
 [5 5 5]
 [3 2 8]]


delete

In [38]:
print(a1)
a2=np.delete(a1,2)
print(a2)

[[1 1 1]
 [5 5 5]
 [3 2 8]]
[1 1 5 5 5 3 2 8]


In [39]:
print(a2)
b2=np.delete(a2,1, axis=0)
print(b2)

[1 1 5 5 5 3 2 8]
[1 5 5 5 3 2 8]


copy() -- if not use copy, they use same memory so that original could be changed when the other are modulated.

In [44]:
print(a1)
print(a1[:2])
a2_sub = a2[:2]
print(a2_sub)

[[1 1 1]
 [5 5 5]
 [3 2 8]]
[[1 1 1]
 [5 5 5]]
[1 1]


In [45]:
print(a2)
a2_sub_copy=a2[:2].copy()
print(a2_sub_copy)

[1 1 5 5 5 3 2 8]
[1 1]


Transpose

In [47]:
print(a1)
print(a1.T)

[[1 1 1]
 [5 5 5]
 [3 2 8]]
[[1 5 3]
 [1 5 2]
 [1 5 8]]


reshape

In [49]:
n1=np.arange(1,10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
print(n1)
print(n1[np.newaxis,:5])
print(n1[:5,np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [54]:
n2 = np.random.randint(0,10, (2,5))
print(n2)
n2.resize((5,2))
print(n2)

[[8 6 5 0 3]
 [0 1 2 2 4]]
[[8 6]
 [5 0]
 [3 0]
 [1 2]
 [2 4]]


resize - remain area are filled with zero

In [55]:
n2.resize((5,5))
print(n2)

[[8 6 5 0 3]
 [0 1 2 2 4]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [56]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.arange(1,10).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
c2 = np.append(a2, b2, axis=0)
print(c2)



[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


concatenate()

In [60]:
np.concatenate([a2,b2])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

np.vstack(), np.hstack(), np.dstack(), stack()

In [61]:
np.hstack([a2,b2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [62]:
np.vstack([a2,b2])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
np.stack([a2,b2])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

split(), vsplit(), hsplit(), dsplit()

In [65]:
b1, c1=np.split(a1, [5])
print(b1,c1)

[[1 1 1]
 [5 5 5]
 [3 2 8]] []


In [67]:
b1, c1=np.vsplit(a1, [5])
print(b1,c1)

[[1 1 1]
 [5 5 5]
 [3 2 8]] []


numpy calculation    broad casting

In [68]:
a1 = np.array([1,2,3])
print(a1)
print(a1+5)

[1 2 3]
[6 7 8]


In [69]:
a2 = np.array([3,5,6])
print(a1+a2)
print(a1-a2)
print(a1*a2)

[4 7 9]
[-2 -3 -3]
[ 3 10 18]


arithmetic operators

In [73]:
print(np.add(a1,10))
print(np.subtract(a1,6))
print(np.multiply(a1,2))
print(np.divide(a1,5))

[11 12 13]
[-5 -4 -3]
[2 4 6]
[0.2 0.4 0.6]


exponential and log fuction

In [74]:
a1 = np.random.randint(1,10, size=5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1,2))

[9 3 5 1 2]
[8.10308393e+03 2.00855369e+01 1.48413159e+02 2.71828183e+00
 7.38905610e+00]
[512.   8.  32.   2.   4.]
[81  9 25  1  4]


In [76]:
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))

[ 0.41211849  0.14112001 -0.95892427  0.84147098  0.90929743]
[-0.91113026 -0.9899925   0.28366219  0.54030231 -0.41614684]
[-0.45231566 -0.14254654 -3.38051501  1.55740772 -2.18503986]


sum() - sum all of element in dimention

In [78]:
print(a2.sum(), np.sum(a1))

14 20


In [79]:
print(np.diff(a2))

[2 1]


In [81]:
print(np.var(a2))
print(np.min(a1))

1.5555555555555554
1


In [87]:
print(np.any(a2>5))
print(np.any(a2 >5,axis=0))

True
True


In [89]:
print((a2>5) & (a2< 8))
print((a2>5) | (a2< 8))

[False False  True]
[ True  True  True]


save and load

In [90]:
np.save("a",a2)

In [91]:
!ls

a.npy  sample_data


In [92]:
np.savez("ab",a2,b2)

In [93]:
!ls

ab.npz	a.npy  sample_data


In [94]:
npy=np.load("a.npy")
print(npy)

[3 5 6]


In [98]:
np.savetxt("a.csv",a2, delimiter=',')

In [99]:
!cat a.csv

3.000000000000000000e+00
5.000000000000000000e+00
6.000000000000000000e+00


In [100]:
csv=np.loadtxt("a.csv", delimiter=',')
print(csv)

[3. 5. 6.]
